#!/bin/sh
PYTHON_PATH=$(/var/packages/TvShowWatch/scripts/bashconstant.py "python_path" < /var/packages/TvShowWatch/target/directory.json )

# Backup Crontab because we are nice
cp /etc/crontab /root/crontab_backup

# Install depedency modules
${PYTHON_PATH}/easy_install tvdb_api transmissionrpc requests cherrypy

exit 0

