#!/bin/sh

TSW_PATH=$(/var/packages/TvShowWatch/scripts/bashconstant.py "tsw_path" < /var/packages/TvShowWatch/target/directory.json )

./start-stop-status stop
sleep 1

rm -rf ${TSW_PATH}/jsonConfigParser

exit 0
