#!/bin/sh
PYTHON_PATH=$(/var/packages/TvShowWatch/scripts/bashconstant.py "python_path" < /var/packages/TvShowWatch/target/directory.json )
TSW_PATH=$(/var/packages/TvShowWatch/scripts/bashconstant.py "tsw_path" < /var/packages/TvShowWatch/target/directory.json )
LOG_PATH=$(/var/packages/TvShowWatch/scripts/bashconstant.py "log_path" < /var/packages/TvShowWatch/target/directory.json )

# Backup Crontab because we are nice
cp /etc/crontab /root/crontab_backup

# Install depedency modules
${PYTHON_PATH}/easy_install tvdb_api transmissionrpc requests cherrypy

# Install paramPy module
wget "https://github.com/kavod/paramPy/releases/download/v1.0/paramPy.tar.gz" -q -O "${TSW_PATH}/paramPy.tar.gz"
tar zxf "${TSW_PATH}/paramPy.tar.gz" -C "${TSW_PATH}"
rm ${TSW_PATH}/paramPy.tar.gz >> ${LOG_PATH}/TSW.log 2>&1

exit 0

