#!/bin/sh
PYTHON_PATH=$(/var/packages/TvShowWatch/scripts/bashconstant.py "python_path" < /var/packages/TvShowWatch/target/directory.json )
TSW_PATH=$(/var/packages/TvShowWatch/scripts/bashconstant.py "tsw_path" < /var/packages/TvShowWatch/target/directory.json )
LOG_PATH=$(/var/packages/TvShowWatch/scripts/bashconstant.py "log_path" < /var/packages/TvShowWatch/target/directory.json )

# Backup Crontab because we are nice
cp /etc/crontab /root/crontab_backup

# Install depedency modules
${PYTHON_PATH}/easy_install tvdb_api transmissionrpc requests cherrypy jsonschema

# Install paramPy module
wget "https://github.com/kavod/jsonConfigParser/releases/download/v1.3/jsonConfigParser_v1.3.tar.gz" -q -O "${TSW_PATH}/jsonConfigParser.tar.gz"
tar zxf "${TSW_PATH}/jsonConfigParser.tar.gz" -C "${TSW_PATH}"
rm ${TSW_PATH}/jsonConfigParser.tar.gz

exit 0

